/** Convert brief Markdown to a styled HTML email body. */

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function inlineMd(text: string): string {
  return escapeHtml(text)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code style=\"background:#f1f5f9;padding:2px 4px;border-radius:4px;font-size:13px\">$1</code>")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "<a href=\"$2\" style=\"color:#0284c7\">$1</a>");
}

export function markdownToEmailHtml(markdown: string, meta: { topicId: string; topicName?: string }): string {
  const lines = markdown.split("\n");
  const blocks: string[] = [];
  let listItems: string[] = [];

  const flushList = () => {
    if (listItems.length) {
      blocks.push(`<ul style="margin:0 0 16px;padding-left:20px;color:#334155;line-height:1.6">${listItems.map((li) => `<li style="margin-bottom:8px">${inlineMd(li)}</li>`).join("")}</ul>`);
      listItems = [];
    }
  };

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) {
      flushList();
      continue;
    }
    if (/^#{1,3}\s+/.test(line)) {
      flushList();
      const text = line.replace(/^#{1,3}\s+/, "");
      blocks.push(`<h2 style="margin:24px 0 8px;font-size:18px;color:#0f172a;font-weight:600">${inlineMd(text)}</h2>`);
      continue;
    }
    if (/^[-*+]\s+/.test(line)) {
      listItems.push(line.replace(/^[-*+]\s+/, ""));
      continue;
    }
    flushList();
    blocks.push(`<p style="margin:0 0 12px;color:#334155;line-height:1.65;font-size:15px">${inlineMd(line)}</p>`);
  }
  flushList();

  const title = meta.topicName ?? meta.topicId;
  return `<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f8fafc">
<div style="max-width:640px;margin:0 auto;padding:32px 24px;font-family:system-ui,-apple-system,sans-serif">
  <div style="border-bottom:2px solid #38bdf8;padding-bottom:16px;margin-bottom:24px">
    <p style="margin:0;font-size:12px;letter-spacing:0.12em;text-transform:uppercase;color:#64748b">Lighthouse daily brief</p>
    <h1 style="margin:8px 0 0;font-size:24px;color:#0f172a">${escapeHtml(title)}</h1>
  </div>
  ${blocks.join("\n")}
  <p style="margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8">
    Generated by Lighthouse · BYOK research digest
  </p>
</div></body></html>`;
}
